#!/bin/bash
# kdtree_for_each_range for non-empty subset

trap "/usr/bin/killall -q -u $USER ./Unit 2>/dev/null" 0 1 2 3 9 15
trap "/bin/rm -f $STDERR" 0 1 2 3 9 15
if [ ! -x ./Unit ]; then
  echo './Unit is missing or not executable'
  echo './Unit is missing or not executable' 1>&2
  exit 1
fi


/c/cs474/bin/run -stdout=stdout.out -stderr=/dev/null ./Unit 7 < /dev/null
cat stdout.out  | /usr/bin/sort -n
